[tool.poetry]
name = "stomark"
version = "1.0.0"
description = "stomark"
authors = ["Sumanth Lingappa <sumanth.lingappa@gmail.com.com>"]

[tool.poetry.dependencies]
pandas = "1.1.4"
python = "^3.8"
yahoofinancials = "1.6"
