[tool.poetry]
name = "stomark"
version = "1.0.1"
description = "stomark"
authors = ["Sumanth Lingappa <sumanth.lingappa@gmail.com.com>"]

[tool.poetry.dependencies]
python = "^3.8"
yahoofinancials = "1.6"
prettytable = "2.0"
